---

- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - redis-tools
      - python-pip
      - virtualenv
      - tmux
      - sqlite3
      - jq
      - bc
      - python3
      - python-dev
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - python-pip
