---

- name: Check if DisasterRecord Exists
  stat:
    path: ~/workspace/DisasterRecord/README.md
  register: DisasterRecord_init

- name: Check if DisasterRecord VE Exists
  stat:
    path: ~/workspace/DisasterRecord/bin/activate
  register: DisasterRecordVE_init

- name: Clone DisasterRecord
  git:
    repo: https://github.com/shrutikar/DisasterRecord.git
    dest: ~/workspace/DisasterRecord
    version: integration
  when: DisasterRecord_init.stat.exists == False

- name: Create DisasterRecord virtualenv
  command: virtualenv -p python3 ~/workspace/DisasterRecord
  when: DisasterRecordVE_init.stat.exists == False

# COPY DisasterRecord REPLACEMENT CODE

- name: Copy fixed DisasterRecord/requirements.txt file to ~/workspace/DisasterRecord
  copy: src=DisasterRecord/requirements.txt dest=~/workspace/DisasterRecord/requirements.txt owner=root group=root mode=0644

- name: Copy fixed DisasterRecord/make.sh file to ~/workspace/DisasterRecord
  copy: src=DisasterRecord/make.sh dest=~/workspace/DisasterRecord/make.sh owner=root group=root mode=0755

#- name: Copy fixed DisasterRecord/core.py file to ~/workspace/DisasterRecord
#  copy: src=DisasterRecord/core.py dest=~/workspace/DisasterRecord/core.py owner=root group=root mode=0644

- name: Generate core.py
  template: src=DisasterRecord/core.py.j2 dest=~/workspace/DisasterRecord/core.py owner=root group=root mode=0644

- name: Generate file-mapping.sh
  template: src=DisasterRecord/file-mapping.sh.j2 dest=~/workspace/DisasterRecord/file-mapping.sh owner=root group=root mode=0755

- name: Generate osm-mapping.sh
  template: src=DisasterRecord/osm-mapping.sh.j2 dest=~/workspace/DisasterRecord/osm-mapping.sh owner=root group=root mode=0755

- name: Generate tweet-mapping.sh
  template: src=DisasterRecord/tweet-mapping.sh.j2 dest=~/workspace/DisasterRecord/tweet-mapping.sh owner=root group=root mode=0755

- name: Copy fixed DisasterRecord/requirements.txt file to ~/workspace/DisasterRecord
  copy: src=DisasterRecord/requirements.txt dest=~/workspace/DisasterRecord/requirements.txt owner=root group=root mode=0644

- name: Create mike_img directory
  file:
    path: ~/workspace/DisasterRecord/mike_img
    state: directory

- name: Create mike_img/models directory
  file:
    path: ~/workspace/DisasterRecord/mike_img/models
    state: directory

- name: Create mike_img/models/flood directory
  file:
    path: ~/workspace/DisasterRecord/mike_img/models/flood
    state: directory

- name: Copy fixed DisasterRecord/load_pb.py file to ~/workspace/DisasterRecord/mike_img
  copy: src=DisasterRecord/load_pb.py dest=~/workspace/DisasterRecord/mike_img/load_pb.py owner=root group=root mode=0644

- name: Copy fixed DisasterRecord/server.py file to ~/workspace/DisasterRecord
  copy: src=DisasterRecord/server.py dest=~/workspace/DisasterRecord/server.py owner=root group=root mode=0644

- name: Install xlrd
  pip: 
    name: xlrd
    virtualenv: ~/workspace/DisasterRecord

- name: Install tweepy
  pip: 
    name: tweepy
    virtualenv: ~/workspace/DisasterRecord

- name: Install python-geohash
  pip: 
    name: python-geohash
    virtualenv: ~/workspace/DisasterRecord

- name: Install elasticsearch_dsl
  pip: 
    name: elasticsearch_dsl
    virtualenv: ~/workspace/DisasterRecord

- name: Install watson_developer_cloud
  pip: 
    name: watson_developer_cloud
    virtualenv: ~/workspace/DisasterRecord

- name: Install tensorflow
  pip: 
    name: tensorflow
    virtualenv: ~/workspace/DisasterRecord

- name: Install Other DisasterRecord dependencies
  pip: 
    requirements: ~/workspace/DisasterRecord/requirements.txt
    virtualenv: ~/workspace/DisasterRecord

- name: Install LNEx dependencies for DisasterRecord
  pip: 
    requirements: ~/workspace/LNEx/requirements.txt
    virtualenv: ~/workspace/DisasterRecord

- name: Create symbolic link for LNEx
  file:
    src: "/root/workspace/LNEx/LNEx"
    dest: "/root/workspace/DisasterRecord/LNEx"
    state: link

- name: Check if DisasterRecord ObjectDetection Exists
  stat:
    path: ~/workspace/DisasterRecord/object_detection
  register: DisasterRecordOD_init

- name: Clone Tensorflow-ImageObjects-Summarizer
  git:
    repo: https://github.com/halolimat/Tensorflow-ImageObjects-Summarizer
    dest: ~/workspace/DisasterRecord/OBJTMP
  when: DisasterRecordOD_init.stat.exists == False

- name: Move object_detection/ back a folder
  command: mv /root/workspace/DisasterRecord/OBJTMP/object_detection /root/workspace/DisasterRecord/object_detection
  when: DisasterRecordOD_init.stat.exists == False

- name: Remove OBJTMP
  command: rm -r /root/workspace/DisasterRecord/OBJTMP
  when: DisasterRecordOD_init.stat.exists == False

- name: Copy fixed DisasterRecord/object_detection/ObjectDetector.py file to ~/workspace/DisasterRecord/object_detection
  copy: src=DisasterRecord/ObjectDetector.py dest=~/workspace/DisasterRecord/object_detection/ObjectDetector.py owner=root group=root mode=0644

- name: Copy DisasterRecord/flood.pb file to ~/workspace/DisasterRecord/mike_img
  copy: src=DisasterRecord/flood.pb dest=~/workspace/DisasterRecord/mike_img/models/flood/flood.pb owner=root group=root mode=0644

- name: Copy DisasterRecord/classes.txt file to ~/workspace/DisasterRecord/mike_img
  copy: src=DisasterRecord/classes.txt dest=~/workspace/DisasterRecord/mike_img/models/flood/classes.txt owner=root group=root mode=0644

- name: Copy DisasterRecord/drEnv file to ~/workspace/DisasterRecord
  copy: src=DisasterRecord/drEnv dest=~/workspace/DisasterRecord/drEnv owner=root group=root mode=0755

- name: Copy startDR-Backend file to ~
  copy: src=DisasterRecord/startDR-Backend dest=~ owner=root group=root mode=0755

- name: Copy killDR-Backend file to ~
  copy: src=DisasterRecord/killDR-Backend dest=~ owner=root group=root mode=0755

- name: Copy startDR-Frontend file to ~
  copy: src=DisasterRecord/startDR-Frontend dest=~ owner=root group=root mode=0755

- name: Copy killDR-Frontend file to ~
  copy: src=DisasterRecord/killDR-Frontend dest=~ owner=root group=root mode=0755

- name: Copy DisasterRecord/static/js/map.js file to ~/workspace/DisasterRecord/static/js
  copy: src=DisasterRecord/static/js/map.js dest=~/workspace/DisasterRecord/static/js/map.js owner=root group=root mode=0644

- name: Copy DisasterRecord/templates/index.html file to ~/workspace/DisasterRecord/templates
  copy: src=DisasterRecord/templates/index.html dest=~/workspace/DisasterRecord/templates/index.html owner=root group=root mode=0644

- name: Copy DisasterRecord/static/alert.png file to ~/workspace/DisasterRecord/static
  copy: src=DisasterRecord/static/alert.png dest=~/workspace/DisasterRecord/static/alert.png owner=root group=root mode=0644

- name: Copy DisasterRecord/static/drone.png file to ~/workspace/DisasterRecord/static
  copy: src=DisasterRecord/static/drone.png dest=~/workspace/DisasterRecord/static/drone.png owner=root group=root mode=0644

- name: Copy DisasterRecord/static/car.png file to ~/workspace/DisasterRecord/static
  copy: src=DisasterRecord/static/car.png dest=~/workspace/DisasterRecord/static/car.png owner=root group=root mode=0644